### ISSUE TITLE
activeScreenArray undefined with SideMenu

### ISSUE THREAD

**Issue by thalesgaldino** [manicantic/react-native-navigation-redux-integration#1]
I'm getting `activeScreenArray undefined` when I look the redux store after setting the root.

Here is my set up:

### Environment
* react-native-navigation-redux-integration: 0.3.4
* React Native Navigation version: 2.1.3
* React Native version: 0.57.4 
* Platform(s) (iOS, Android, or both?): Android at least
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

My index:

```
Navigation.setRoot({
    root: {
      sideMenu: {
        center: {
          stack: {
            children: [
              {
                component: {
                  name: ROOT_SCREEN,
                },
              },
            ],
          },
        },
      },
    },
  });
});
```

P.S.: I tried without sideMenu and worked. But I do need the sideMenu :)

**Comment by manicantic** [comment]
Hi @thalesgaldino , I tried to reproduce issue with your environment, but I wasn't able to, I am getting right store state after setting sideMenu layout root. Did you maybe check if both actions `@NAVIGATOR/ROOT_SET` and `@NAVIGATOR/SCREEN_APPEARED` appeared in your reducer after setting root? Because activeScreenArray is managed by RNN screen appeared listener.

**Comment by thalesgaldino** [comment]
@manicantic, I just figured out this: if I use customs right top buttons, like this:

```
Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        rightButtons: [{
        id: 'menu',
        text: 'Menu',
        component: {
          name: ICON_MENU,
          passProps: {
            icon,
          },
        },
      }]
```

This will "undefine" the `activeScreenArray`

Do you know any workaround? Or can't I use mergeOptions?

**Comment by manicantic** [comment]
Thanks @thalesgaldino , I will check out this today and push a fix.

**Comment by manicantic** [comment]
@thalesgaldino I pushed new version 0.3.6. Did you maybe user mergeOptions for changing between top tabs ?

**Comment by thalesgaldino** [comment]
no sure what you mean, but im using mergeOptions for different component screens that have a menu action

**Comment by manicantic** [comment]
Did you use something like :
```javascript
Navigation.mergeOptions(this.props.componentId, {
  topTabs: {
    currentTabId: this.props.componentId
  }
});
```
 Did you try upgrading to 0.3.6 ?

**Comment by thalesgaldino** [comment]
I'm using exactly the example I post previously. But I haven't tried 0.3.6 yet. Won't be able to try it out for some time, because I'm other project currently. But thanks for that new version. Will let you know when I get back to it 👍
