### ISSUE TITLE
activeScreenArray undefined when in modal -> native sms/email -> modal

### ISSUE THREAD

**Issue by newah** [manicantic/react-native-navigation-redux-integration#4]
We've been using your lib quite intensively. It's great.

But we faced a very cornercase issue:
1) we have a modal screen
2) open a iOS native sms/email screen @NAVIGATOR/SCREEN_DISAPPEARED is called
3) come back to the app the modal screen is not in the navigation store anymore. It's been removed. So now `activeScreenArray is undefined` and empty `modals: []`

**Comment by manicantic** [comment]
Hi @newah , thanks for bug report. One question, does @NAVIGATOR/SCREEN_APPEARED get called once you go back to your app ?

**Comment by newah** [comment]
Hey @manicantic, yes, it gets called. 

But the screen isn’t among modals anymore and active screens is undefined (not even an empty array). And I think it doesn’t recover after getting the screen appeared event

**Comment by manicantic** [comment]
Yes, because it "disappears", but actually app goes to background ( another apps appears ). Not sure it this is RNN bug. Do you maybe have any redux tools ? Can you screen me state and action in every step ?

**Comment by BDomantas** [comment]
Hello, I have encountered the same problem with react-native-image-picker. After returning from camera back to app causes crash because ActiveScreenArray is undefined and then navigating to another screen causes crash because it tries to access [0] element of ActiveScreenArray in getActiveScreenId function
