### ISSUE TITLE
How can we .showModal?

### ISSUE THREAD

**Issue by SudoPlz** [manicantic/react-native-navigation-redux-integration#6]
Hey there,

is that functionality missing?
If so how can I do that?

Thank you.

**Comment by SudoPlz** [comment]
My bad it's called `setStackRoot` and it's there.

**Comment by manicantic** [comment]
Hi @SudoPlz , yes it was missing but I've just added it. Didn't have time to test, so if you could test and write a feedback that would be great :)

**Comment by wardjk87** [comment]
@manicantic It doesn't look like showModal is being exported by the root index file.

**Comment by manicantic** [comment]
@wardjk87 Nice catch, I will add export of this today.
